config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pantry.apps.users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", user_views.UserRegisterView.as_view(), name="register"),
    path("login/", user_views.UserLoginView.as_view(), name="login"),
    path("logout/", user_views.UserLogoutView.as_view(), name="logout"),
    path("", include("pantry.apps.recipes.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pantry/apps/recipes/urls.py
from django.urls import path
from .views import (
    AboutView,
    RecipeListView,
    RecipeDetailView,
    RecipeCreateView,
)

app_name = "recipes"

urlpatterns = [
    path("", RecipeListView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("recipes/", RecipeListView.as_view(), name="recipes"),
    path(
        "recipe/<int:pk>/",
        RecipeDetailView.as_view(),
        name="detail",
    ),
    path(
        "recipe/new/",
        RecipeCreateView.as_view(),
        name="create",
    ),
]

pantry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pantry.apps.users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.UserRegisterView.as_view(), name='register'),
    path('login/', user_views.UserLoginView.as_view(), name='login'),
    path('logout/', user_views.UserLogoutView.as_view(), name='logout'),
    path('', include('pantry.apps.recipes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.apps.recipes.urls')),
]

if settings.DEBUG:
    urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('recipes/', include('recipes.apps.recipes.urls')),
    path('admin/', admin.site.urls),
]

simplerecipes/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

pantry/apps/recipes/models.py
from django.db import models
from django.contrib.auth.models import User

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Ingredient(models.Model):
    """
    Represents the ingredient model.
    """

    name = models.CharField(max_length=128, unique=True, db_index=True)

    class Meta:
        verbose_name_plural = "ingredients"

    def __str__(self):
        return self.name


class Recipe(models.Model):
    """
    Represents the recipe model.
    """

    name = models.CharField(max_length=128, unique=True, db_index=True)
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    image = models.ImageField(blank=True, upload_to="recipes", default="")
    image_thumbnail = ImageSpecField(
        source="image",
        processors=[ResizeToFill(640, 480)],
        format="JPEG",
        options={"quality": 60},
    )
    description = models.TextField(blank=True)
    ingredients = models.ManyToManyField(
        Ingredient,
        blank=True,
    )
    method = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "recipes"

    def __str__(self):
        return self.name

pantry/apps/recipes/forms.py
from django import forms

from .models import Recipe


class RecipeCreateForm(forms.ModelForm):
    """
    A form containing form fields for creating a new recipe.
    """

    class Meta:
        model = Recipe
        exclude = ["author"]

pantry/apps/users/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.auth.forms import UsernameField
from django.utils.translation import gettext_lazy as _


class UserRegisterForm(forms.ModelForm):
    """
    A form containing form fields for register a new user.
    """

    email = forms.EmailField(label=_("Email"))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=_(
            "Make sure it's at least 8 characters including a number and a lowercase letter."
        ),
    )

    class Meta:
        model = User
        fields = ["username", "email", "password"]
        field_classes = {"username": UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["autofocus"] = True
        self.fields["username"].help_text = ""

    def clean_email(self):
        email = self.cleaned_data["email"]
        # check for the same email
        user = User.objects.filter(email=email).first()
        if user is not None:
            raise forms.ValidationError(_("A user with that email already exists."))
        return email

    def _post_clean(self):
        super()._post_clean()
        password = self.cleaned_data.get("password")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except forms.ValidationError as error:
                self.add_error("password", error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

pantry/apps/recipes/views.py
from django.urls import reverse_lazy
from django.views import generic

from .models import Recipe
from .forms import RecipeCreateForm


class AboutView(generic.TemplateView):
    """
    A view for displaying a description of a site.
    """
    template_name = 'recipes/about.html'


class RecipeListView(generic.ListView):
    """
    A view for displaying a list of recipes.
    """
    model = Recipe
    template_name = 'recipes/recipes.html'
    context_object_name = 'recipes'
    ordering = ['name']


class RecipeDetailView(generic.DetailView):
    """
    A view for displaying a recipe.
    """
    model = Recipe
    template_name = 'recipes/detail.html'


class RecipeCreateView(generic.CreateView):
    """
    A view for creating a new recipe.
    """
    form_class = RecipeCreateForm
    template_name = 'recipes/new.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('recipes:detail', kwargs={'pk': self.object.pk})

pantry/apps/users/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView
from django.utils.translation import gettext_lazy as _

from .forms import UserRegisterForm


class UserRegisterView(CreateView):
    """
    A view for registration a new user.
    """

    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        messages.success(self.request, _("Your account has been created."))
        return super().form_valid(form)


class UserLoginView(LoginView):
    """
    A view for login user.
    """

    template_name = "users/login.html"


class UserLogoutView(LogoutView):
    """
    A view for logout user.
    """

    template_name = "users/logout.html"

    def get(self, request, *args, **kwargs):
        messages.info(self.request, _("You have been logged out."))
        return super().get(self, request, *args, **kwargs)

recipes/apps/recipes/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(reques):
    return HttpResponse('Index')

pantry/apps/recipes/templates/recipes/about.html
{% extends 'recipes/base.html' %}

{% block title %}
    <title>About</title>
{% endblock title %}

{% block content %}
    <div class="container">
        <h1>About</h1>
    </div>
{% endblock content %}

pantry/apps/recipes/templates/recipes/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'recipes/main.css' %}">

    <!-- Title -->
    {% block title %}
        <title>Pantry</title>
    {% endblock title %}

</head>

<body>

<!-- Header -->
<header>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'recipes:home' %}">Pantry</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <!-- Navbar Left Side -->
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'recipes:recipes' %}">Recipes</a>
                    <a class="nav-item nav-link" href="{% url 'recipes:about' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'recipes:create' %}">New Recipe</a>
                        <div class="dropdown">
                            <a class="nav-item nav-link dropdown-toggle" href="#" role="button"
                               id="dropdownUserMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownUserMenu">
                                <a class="dropdown-item" href="#">Your profile</a>
                                <a class="dropdown-item" href="#">Your recipes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Sign out</a>
                            </div>
                        </div>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Sign in</a>
                        <a class="nav-item nav-link border border-secondary rounded" href="{% url 'register' %}">Sign
                            up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<!-- Main -->
<main role="main" class="mt-5">
    <div class="py-5 bg-light">
        <div class="container">
            <div class="mx-auto col-md-6">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            </div>
            {% block content %}{% endblock content %}
        </div>
    </div>
</main>

<!-- Footer -->
<footer class="mt-3">
    <div class="container">
        <p class="text-muted text-center">&copy; 2020 Pantry</p>
    </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

</body>

</html>

pantry/apps/recipes/templates/recipes/detail.html
{% extends 'recipes/base.html' %}

{% block title %}
    <title>{{ recipe.name }}</title>
{% endblock title %}

{% block content %}
    <div class="row">
        <!-- Main card -->
        <div class="col-md-8 mb-3">
            <div class="card shadow-sm">
                {% if recipe.image %}
                    <img class="card-img-top recipe-detail-img rounded-0" src="{{ recipe.image_thumbnail.url }}"
                         alt="thumbnail">
                {% else %}
                    <svg class="card-img-top recipe-detail-img">
                        <rect width="100%" height="100%" fill="#55595c"></rect>
                        <text text-anchor="middle" x="50%" y="50%" fill="#eceeef">Thumbnail</text>
                    </svg>
                {% endif %}
                <div class="card-body">
                    <h1 class="card-title text-center border-bottom pb-3">
                        {{ recipe.name }}
                    </h1>
                    <p class="card-text text-center">
                        {{ recipe.description }}
                    </p>
                    <!-- Ingredients -->
                    <h4 class="card-text text-center mt-3">What You Need</h4>
                    <ul class="list-group">
                        {% for ingredient in recipe.ingredients.all %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ ingredient.name }}
                                <span class="badge badge-dark badge-pill">99</span>
                            </li>
                        {% endfor %}
                    </ul>
                    <!-- Directions -->
                    <h4 class="card-text text-center mt-3">Directions</h4>
                    <p class="card-text text-center">
                        {{ recipe.method }}
                    </p>
                </div>
            </div>
        </div>
        <!-- Sidebar -->
        <div class="col-md-4">
            <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Sidebar action 1</h6>
                        <small class="text-muted">description</small>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Sidebar action 2</h6>
                        <small class="text-muted">description</small>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Sidebar action 3</h6>
                        <small class="text-muted">description</small>
                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endblock content %}

pantry/apps/recipes/templates/recipes/new.html
{% extends 'recipes/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>New Recipe</title>
{% endblock title %}

{% block content %}
    <div class="d-md-flex flex-items-center">
        <!-- Main card -->
        <div class="mx-auto col-sm-8 col-md-6 mb-3">
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">New Recipe</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

pantry/apps/recipes/templates/recipes/recipes.html
{% extends 'recipes/base.html' %}

{% block title %}
    <title>Recipes</title>
{% endblock title %}

{% block content %}
    <!-- Cards with recipes -->
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3">
        {% for recipe in recipes %}
            <div class="col mb-4">
                <!-- Card with a specific recipe -->
                <div class="card h-100 shadow-sm">
                    {% if recipe.image %}
                        <img class="card-img-top recipe-list-img rounded-0" src="{{ recipe.image_thumbnail.url }}"
                             alt="Thumbnail">
                    {% else %}
                        <svg class="card-img-top recipe-list-img">
                            <rect width="100%" height="100%" fill="#55595c"></rect>
                            <text text-anchor="middle" x="50%" y="50%" fill="#eceeef">Thumbnail</text>
                        </svg>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            {{ recipe.name }}
                        </h5>
                        <p class="card-text text-center">
                            {{ recipe.description }}
                        </p>
                    </div>
                    <a class="card-link stretched-link" href="{% url 'recipes:detail' recipe.id %}"></a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

pantry/apps/users/templates/users/login.html
{% extends 'recipes/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="d-md-flex flex-items-center">
        <div class="mx-auto col-sm-6">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log In</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit">Sign in</button>
                </div>
            </form>
            <div class="border-top pt-3 text-center">
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up!</a>
                </small>
            </div>
        </div>
    </div>
{% endblock content %}

pantry/apps/users/templates/users/logout.html
{% extends 'recipes/base.html' %}

{% block content %}
    <div class="d-md-flex flex-items-center">
        <div class="mx-auto col-md-6">
            <div class="border-top pt-3">
                <p>Thanks for spending some quality time with the site!</p>
                <small class="text-muted">
                    <a href="{% url 'login' %}">Log In Again</a>
                </small>
            </div>
        </div>
    </div>
{% endblock content %}

pantry/apps/users/templates/users/register.html
{% extends 'recipes/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="d-md-flex flex-items-center">
        <div class="mx-auto col-md-6">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Join Today</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit">Sign up</button>
                </div>
            </form>
            <div class="border-top pt-3 text-center">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                </small>
            </div>
        </div>
    </div>
{% endblock content %}

project/apps/recipes/templates/recipes/index.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <title>Recipes</title>

</head>

<body>
  <!-- Header -->
  <header>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="#">Simple cook</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
          <!-- Navbar Left Side -->
          <a class="nav-item nav-link" href="#">Home</a>
            <a class="nav-item nav-link" href="#">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="#">Login</a>
            <a class="nav-item nav-link" href="#">Register</a>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <!-- Main -->
  <main role="main" class="my-5">
    <div class="py-5 bg-light">
      <div class="container">
        <div class="row">
          <!-- Cards with recipes -->
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {% for recipe in recipes %}
            <div class="col">
              <!-- Card with a specific recipe -->
              <div class="card mb-4 shadow-sm" style="height: 24rem;">
                <div class="card-header text-center">
                  {{ recipe.name }}
                </div>
                <img src="{{ recipe.image.url }}" class="card-img-top rounded-0">
                <div class="card-body">
                  <p class="card-text">{{ recipe.description }}</p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </main>
  <!-- Footer -->
  <footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <a href="#">Back to top</a>
      </p>
      <p>{% lorem 8 w %}</p>
    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>
</body>

</html>